name: jinni # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

#build-packages: [python3-dev, python3-setuptools, libtool, libffi-dev, libssl-dev, autoconf, build-essential]

parts:
  alsa-mixin:
    build-packages:
      - libasound2-dev
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    stage-packages:
      - libslang2
      - libasound2
      - libasound2-plugins
      - libportaudio2
      - pulseaudio
      - alsa-utils
      - yad

  jinni:
    after: [alsa-mixin]
    plugin: dump
    source: .
    override-build: |
      sudo scripts/bashScripts/nativeExecutableMaker.sh  # Downloading dart-sdk for the correct architecture.

      #cd scripts/bashScripts/
      #./compileAllCFiles.sh # Have to be executed when working directory is this file location
      #cd ../..

      rm -r Assistant

      snapcraftctl build

    build-packages:
      - wget
      - unzip
      - git
      - gcc
      - g++
      - make
      - libatlas-base-dev
      - libasound-dev
    stage-packages:
      - libatlas-base-dev
      - libevent-dev


#  python-code:
#    plugin: python
#    source: scripts/pythonScripts/voiceAssistence/
#    python-version: python3
#    build-packages:
#      - python3-pip
#    #stage-packages:
#    #  - python-six

layout: # Taneling the alsa comands inside the snap to the alsa on the device
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

system-usernames:
  snap_daemon: shared

apps:
  jinni:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: main.exe $SNAP
    #daemon: simple
    plugs: [network, network-bind, gpio, hardware-observe, audio-playback, audio-record, pulseaudio, alsa]
